/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./react-ref-assets/**/*.{html,js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./Views/**/*.{cshtml,aspx}",
    "./layouts/**/*.{cshtml,aspx}"
  ],
  safelist: [
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-6',
    'md:grid-cols-2',
    'md:grid-cols-4',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'lg:grid-cols-6',
    'lg:col-span-2',
    'lg:order-1',
    'lg:order-2',
    'gap-8',
    'gap-12',
    'mb-12',
    'mb-8',
    'max-w-4xl',
    'max-w-md',
    'max-w-6xl',
    'max-w-none',
    'mx-auto',
    'mr-auto',
    'ml-auto',
    'text-center',
    'text-left',
    'text-right',
    'items-center',
    'space-y-2',
    'space-y-4',
    'list-disc',
    'list-inside',
    'max-w-2xl',
    'prose',
    'prose-sm',
    'prose-lg',
    'leading-relaxed',
    'shadow-lg',
    'space-y-4',
    'hover-elevate',
    'hover:no-underline',
    'pt-2',
    'mt-12',
    'mb-4',
    'inline-block',
    'hover:bg-primary/90',
    'transition-colors',
    'py-20',
    'overflow-hidden',
    'bg-gradient-to-r',
    'from-primary',
    'via-primary/90',
    'to-blue-600',
    'bg-cover',
    'bg-center',
    'bg-no-repeat',
    'from-primary/90',
    'to-blue-600/90',
    'absolute',
    'inset-0',
    '-top-10',
    '-right-10',
    '-bottom-10',
    '-left-10',
    'w-40',
    'h-40',
    'w-32',
    'h-32',
    'bg-white/10',
    'rounded-full',
    'blur-xl',
    'relative',
    'z-10',
    'text-white',
    'text-white/90',
    'text-4xl',
    'text-5xl',
    'text-6xl',
    'text-xl',
    'text-2xl',
    'lg:text-6xl',
    'md:text-5xl',
    'md:text-2xl',
    'px-8',
    'py-6',
    'sm:flex-row',
    'flex-col',
    'justify-center',
    'hover:scale-105',
    'hover:translate-x-1',
    'transition-transform',
    'border-white',
    'hover:bg-white',
    'hover:text-primary',
    'backdrop-blur-sm',
    'inline-flex',
    'animate-float',
    'animate-float-delayed',
    'justify-center',
    'gap-2',
    'whitespace-nowrap',
    'focus-visible:outline-none',
    'focus-visible:ring-1',
    'focus-visible:ring-ring',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
    '[&_svg]:pointer-events-none',
    '[&_svg]:size-4',
    '[&_svg]:shrink-0',
    'hover-elevate',
    'active-elevate-2',
    'border-primary-border',
    'min-h-10',
    'rounded-md',
    'font-semibold',
    'font-medium',
    '[border-color:var(--button-outline)]',
    'shadow-xs',
    'active:shadow-none',
    'pt-16',
    'mb-16',
    'p-6',
    'text-lg',
    'text-sm',
    'mb-2',
    'h-16',
    'w-auto',
    'object-contain',
    'p-3',
    'duration-300',
    'h-8',
    'w-8',
    'rounded',
    'flex-shrink-0',
    'space-x-3',
    'space-x-1',
    'h-4',
    'w-4',
    'h-12',
    'w-12',
    'text-green-600',
    'text-red-600',
    'bg-green-100',
    'bg-red-100',
    'bg-green-900/20',
    'bg-red-900/20',
    'dark:bg-green-900/20',
    'dark:bg-red-900/20',
    'dark:text-green-400',
    'dark:text-red-400',
    'cursor-pointer',
    'justify-between',
    'rounded-full',
    'bg-muted/20',
    'fill-yellow-400',
    'text-yellow-400',
    'text-gray-300',
    'h-6',
    'w-6',
    'text-primary/20',
    'w-12',
    'h-12',
    'object-cover',
    'mr-4',
    'leading-relaxed',
    'text-xs'
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: ".5625rem", /* 9px */
        md: ".375rem", /* 6px */
        sm: ".1875rem", /* 3px */
      },
      colors: {
        // Flat / base colors (regular buttons)
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        card: {
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
          border: "hsl(var(--card-border) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover) / <alpha-value>)",
          foreground: "hsl(var(--popover-foreground) / <alpha-value>)",
          border: "hsl(var(--popover-border) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground) / <alpha-value>)",
          border: "var(--primary-border)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
          border: "var(--secondary-border)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
          border: "var(--muted-border)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
          border: "var(--accent-border)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
          border: "var(--destructive-border)",
        },
        ring: "hsl(var(--ring) / <alpha-value>)",
        chart: {
          "1": "hsl(var(--chart-1) / <alpha-value>)",
          "2": "hsl(var(--chart-2) / <alpha-value>)",
          "3": "hsl(var(--chart-3) / <alpha-value>)",
          "4": "hsl(var(--chart-4) / <alpha-value>)",
          "5": "hsl(var(--chart-5) / <alpha-value>)",
        },
        sidebar: {
          ring: "hsl(var(--sidebar-ring) / <alpha-value>)",
          DEFAULT: "hsl(var(--sidebar) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-foreground) / <alpha-value>)",
          border: "hsl(var(--sidebar-border) / <alpha-value>)",
        },
        "sidebar-primary": {
          DEFAULT: "hsl(var(--sidebar-primary) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-primary-foreground) / <alpha-value>)",
          border: "var(--sidebar-primary-border)",
        },
        "sidebar-accent": {
          DEFAULT: "hsl(var(--sidebar-accent) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-accent-foreground) / <alpha-value>)",
          border: "var(--sidebar-accent-border)"
        },
        status: {
          online: "rgb(34 197 94)",
          away: "rgb(245 158 11)",
          busy: "rgb(239 68 68)",
          offline: "rgb(156 163 175)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "float": {
          "0%, 100%": { transform: "translate(0, 0)" },
          "33%": { transform: "translate(100px, -50px)" },
          "66%": { transform: "translate(0, 0)" },
        },
        "float-delayed": {
          "0%, 100%": { transform: "translate(0, 0)" },
          "33%": { transform: "translate(-80px, 60px)" },
          "66%": { transform: "translate(0, 0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "float": "float 20s ease-in-out infinite",
        "float-delayed": "float-delayed 15s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
}