declare const styles: {
  readonly financialInstruments: string;
  readonly header: string;
  readonly headerTitle: string;
  readonly headerSubtitle: string;
  readonly mainContainer: string;
  readonly sidebar: string;
  readonly contentArea: string;
  readonly categoryCard: string;
  readonly categoryHeader: string;
  readonly categoryTitle: string;
  readonly categoryCount: string;
  readonly subcategories: string;
  readonly active: string;
  readonly subcategory: string;
  readonly selected: string;
  readonly instrumentGrid: string;
  readonly instrumentCard: string;
  readonly instrumentSymbol: string;
  readonly instrumentName: string;
  readonly instrumentPrice: string;
  readonly instrumentDetails: string;
  readonly detailItem: string;
  readonly detailLabel: string;
  readonly detailValue: string;
  readonly loading: string;
  readonly error: string;
  readonly summaryStats: string;
  readonly statItem: string;
  readonly statNumber: string;
  readonly statLabel: string;
  readonly searchBar: string;
  readonly emptyState: string;
  readonly emptyStateTitle: string;
  readonly emptyStateMessage: string;
};

export default styles;
