---
ID: "7777be38-58b9-46fe-9bc3-b534cee69f08"
Parent: "fc781145-d3c6-4905-98f2-f829e793ccbf"
Template: "fc781145-d3c6-4905-98f2-f829e793ccbf"
Path: "/sitecore/templates/Project/plus-five-hundred/TestLibrary/Datasource/BulletList/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{771ED379-AFA6-411D-9F0F-3758738BF0D7}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "69b33f81-a15d-4c20-a16f-7ed563a9ed25"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250922T202234Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\andiappan.ravi@omnia.ae
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\andiappan.ravi@omnia.ae
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "708ffa89-4ea8-4517-b9a6-3964d4c73240"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andiappan.ravi@omnia.ae
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250922T202234Z
