---
ID: "f0202a25-d5af-4c38-a3bd-01e07dd06ed9"
Parent: "c3dcaa4d-ea0b-4028-a959-5b2ecc420e91"
Template: "c3dcaa4d-ea0b-4028-a959-5b2ecc420e91"
Path: "/sitecore/templates/Project/plus-five-hundred/Component/Plus500/FooterRederingTemplate/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "96e5345a-9ef5-489b-84d8-6bee294608ad"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andiappan.ravi@omnia.ae
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250921T094011Z
